require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PotentialCustomersController do

  # This should return the minimal set of attributes required to create a valid
  # PotentialCustomer. As you add validations to PotentialCustomer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "email" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PotentialCustomersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all potential_customers as @potential_customers" do
      potential_customer = PotentialCustomer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:potential_customers).should eq([potential_customer])
    end
  end

  describe "GET show" do
    it "assigns the requested potential_customer as @potential_customer" do
      potential_customer = PotentialCustomer.create! valid_attributes
      get :show, {:id => potential_customer.to_param}, valid_session
      assigns(:potential_customer).should eq(potential_customer)
    end
  end

  describe "GET new" do
    it "assigns a new potential_customer as @potential_customer" do
      get :new, {}, valid_session
      assigns(:potential_customer).should be_a_new(PotentialCustomer)
    end
  end

  describe "GET edit" do
    it "assigns the requested potential_customer as @potential_customer" do
      potential_customer = PotentialCustomer.create! valid_attributes
      get :edit, {:id => potential_customer.to_param}, valid_session
      assigns(:potential_customer).should eq(potential_customer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PotentialCustomer" do
        expect {
          post :create, {:potential_customer => valid_attributes}, valid_session
        }.to change(PotentialCustomer, :count).by(1)
      end

      it "assigns a newly created potential_customer as @potential_customer" do
        post :create, {:potential_customer => valid_attributes}, valid_session
        assigns(:potential_customer).should be_a(PotentialCustomer)
        assigns(:potential_customer).should be_persisted
      end

      it "redirects to the created potential_customer" do
        post :create, {:potential_customer => valid_attributes}, valid_session
        response.should redirect_to(PotentialCustomer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved potential_customer as @potential_customer" do
        # Trigger the behavior that occurs when invalid params are submitted
        PotentialCustomer.any_instance.stub(:save).and_return(false)
        post :create, {:potential_customer => { "email" => "invalid value" }}, valid_session
        assigns(:potential_customer).should be_a_new(PotentialCustomer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PotentialCustomer.any_instance.stub(:save).and_return(false)
        post :create, {:potential_customer => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested potential_customer" do
        potential_customer = PotentialCustomer.create! valid_attributes
        # Assuming there are no other potential_customers in the database, this
        # specifies that the PotentialCustomer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PotentialCustomer.any_instance.should_receive(:update_attributes).with({ "email" => "MyString" })
        put :update, {:id => potential_customer.to_param, :potential_customer => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested potential_customer as @potential_customer" do
        potential_customer = PotentialCustomer.create! valid_attributes
        put :update, {:id => potential_customer.to_param, :potential_customer => valid_attributes}, valid_session
        assigns(:potential_customer).should eq(potential_customer)
      end

      it "redirects to the potential_customer" do
        potential_customer = PotentialCustomer.create! valid_attributes
        put :update, {:id => potential_customer.to_param, :potential_customer => valid_attributes}, valid_session
        response.should redirect_to(potential_customer)
      end
    end

    describe "with invalid params" do
      it "assigns the potential_customer as @potential_customer" do
        potential_customer = PotentialCustomer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PotentialCustomer.any_instance.stub(:save).and_return(false)
        put :update, {:id => potential_customer.to_param, :potential_customer => { "email" => "invalid value" }}, valid_session
        assigns(:potential_customer).should eq(potential_customer)
      end

      it "re-renders the 'edit' template" do
        potential_customer = PotentialCustomer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PotentialCustomer.any_instance.stub(:save).and_return(false)
        put :update, {:id => potential_customer.to_param, :potential_customer => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested potential_customer" do
      potential_customer = PotentialCustomer.create! valid_attributes
      expect {
        delete :destroy, {:id => potential_customer.to_param}, valid_session
      }.to change(PotentialCustomer, :count).by(-1)
    end

    it "redirects to the potential_customers list" do
      potential_customer = PotentialCustomer.create! valid_attributes
      delete :destroy, {:id => potential_customer.to_param}, valid_session
      response.should redirect_to(potential_customers_url)
    end
  end

end
